language: c++

before_install:
  - sudo apt-get install python-software-properties -y # for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - sudo apt-get install gcc-multilib g++-multilib -y # since VM is 64bit but hxcpp builds 32bit by default
  - sudo apt-get install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev -y # for nme
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib git munit https://github.com/massiveinteractive/MassiveUnit.git
  
  # NME dev
  - haxelib dev nme $(pwd)
  - haxelib git nmedev https://github.com/haxenme/nmedev.git
  - haxelib git swf https://github.com/haxenme/swf.git
  - haxelib git xfl https://github.com/haxenme/xfl.git
  - haxelib install svg
  - haxelib install hxcpp
  - haxelib install format
  - haxelib run nme rebuild tools
  - haxelib run nme rebuild linux
  - mkdir bin

script:
  - test/runTests.sh
