language: c++

before_install:
  - sudo apt-get install python-software-properties -y # for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - sudo apt-get install gcc-multilib g++-multilib -y # since VM is 64bit but hxcpp builds 32bit by default
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install utest
  - haxelib install compiletime
  - haxelib install hxcpp
  - haxelib git kalturhaxe https://github.com/Knowledge-Players/KalturHaxe.git
  - mkdir bin

script:
  - haxe build.hxml
  - tests/results/RunTest-debug
