language: c++

before_install:
  - sudo apt-get install python-software-properties -y # for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - sudo apt-get install gcc-multilib g++-multilib -y # since VM is 64bit but hxcpp builds 32bit by default
  - sudo apt-get install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev -y # for nme
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib git actuate https://github.com/jgranick/actuate.git
  - haxelib git tilelayer https://github.com/JbIPS/nme-tilelayer.git haxelib
  - wget http://lib.haxe.org/files/3.0/nme-3,5,6.zip
  - haxelib local nme-3,5,6.zip

script:
  - haxe build.hxml
